name: CI for Lab1

on:
  push:
    paths:
      - 'lab1/**'
  pull_request:
    paths:
      - 'lab1/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Clojure
      uses: DeLaGuardo/setup-clojure@v1
      with:
        clojure_version: '1.12.0.1479'

    - name: Change working directory
      run: cd lab1 && lein test
