name: CI for Lab2

on:
  push:
    paths:
      - 'lab2/**'
  pull_request:
    paths:
      - 'lab2/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Leiningen
      run: |
        sudo apt-get update
        sudo apt-get install -y leiningen
    
    - name: Change directory and run linting
      run: |
        cd lab2
        lein eastwood
    
    - name: Change directory and run tests
      run: |
        cd lab2
        lein test
